{% set name = "hazpy" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: "."

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - rasterio
    - geopandas
    - pyodbc
    - sqlalchemy
    - urllib3
    - xhtml2pdf
    - utm
    - matplotlib
    - seaborn

test:
  imports:
    - hazpy
    - hazpy.common
    - hazpy.earthquake
    - hazpy.earthquake.modules
    - hazpy.flood
    - hazpy.flood.modules
    - hazpy.hurricane
    - hazpy.hurricane.modules
    - hazpy.legacy
    - hazpy.legacy.common
    - hazpy.legacy.hazusdb
    - hazpy.legacy.studyregion
    - hazpy.legacy.report
    - hazpy.tornado
    - hazpy.tsunami
    - hazpy.tsunami.modules

about:
  home: "https://github.com/nhrap-hazus/hazpy.git"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: 
  summary: "FEMA - hazpy Open-Source Natural Disaster Risk Assessment Package"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - lorax521
    - ujvalak